// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJS8lY0TmbGYsC_S5l7w1dGSfAXff9c8',
    appId: '1:503372608759:web:9c5d9c0c0c53560d08cff2',
    messagingSenderId: '503372608759',
    projectId: 'login-test-15920',
    authDomain: 'login-test-15920.firebaseapp.com',
    storageBucket: 'login-test-15920.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYRoGRTvqpItn_L3lNBy55SnMZTnMVNhE',
    appId: '1:503372608759:android:7085b3d9eceebeeb08cff2',
    messagingSenderId: '503372608759',
    projectId: 'login-test-15920',
    storageBucket: 'login-test-15920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMN7Y0bEaR9pu4PKFw9-_RvSerH7A2D2o',
    appId: '1:503372608759:ios:d67b433de0cd551208cff2',
    messagingSenderId: '503372608759',
    projectId: 'login-test-15920',
    storageBucket: 'login-test-15920.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication13Examen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMN7Y0bEaR9pu4PKFw9-_RvSerH7A2D2o',
    appId: '1:503372608759:ios:d67b433de0cd551208cff2',
    messagingSenderId: '503372608759',
    projectId: 'login-test-15920',
    storageBucket: 'login-test-15920.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication13Examen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJS8lY0TmbGYsC_S5l7w1dGSfAXff9c8',
    appId: '1:503372608759:web:1090f8ed3499e29a08cff2',
    messagingSenderId: '503372608759',
    projectId: 'login-test-15920',
    authDomain: 'login-test-15920.firebaseapp.com',
    storageBucket: 'login-test-15920.firebasestorage.app',
  );
}
