// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5C0NTOs-51BKGSZRkoHqv8Yja6FGnHiU',
    appId: '1:496536698389:web:024795ca6f30185fcf181c',
    messagingSenderId: '496536698389',
    projectId: 'logintest-15920',
    authDomain: 'logintest-15920.firebaseapp.com',
    storageBucket: 'logintest-15920.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKATFc7zDLDsWDQbwEOugxjWYV4hjqwao',
    appId: '1:496536698389:android:c17ae140362ecf49cf181c',
    messagingSenderId: '496536698389',
    projectId: 'logintest-15920',
    storageBucket: 'logintest-15920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnyEKVgham45omWfdVFlYd2G_P-pLKkDQ',
    appId: '1:496536698389:ios:644bf59940afb18dcf181c',
    messagingSenderId: '496536698389',
    projectId: 'logintest-15920',
    storageBucket: 'logintest-15920.firebasestorage.app',
    iosClientId: '496536698389-fmjsq97gf774im06fsp1b6na0407nd89.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnyEKVgham45omWfdVFlYd2G_P-pLKkDQ',
    appId: '1:496536698389:ios:644bf59940afb18dcf181c',
    messagingSenderId: '496536698389',
    projectId: 'logintest-15920',
    storageBucket: 'logintest-15920.firebasestorage.app',
    iosClientId: '496536698389-fmjsq97gf774im06fsp1b6na0407nd89.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5C0NTOs-51BKGSZRkoHqv8Yja6FGnHiU',
    appId: '1:496536698389:web:c70f5601090a96e4cf181c',
    messagingSenderId: '496536698389',
    projectId: 'logintest-15920',
    authDomain: 'logintest-15920.firebaseapp.com',
    storageBucket: 'logintest-15920.firebasestorage.app',
  );
}
